### ISSUE TITLE
No README.md

### ISSUE THREAD

**Issue by joek13** [andrewmccullough/mastermind#1]
Dear Andrew,

While I greatly respect and admire your work, I am alarmed at this repository's lack of a README.md file. New contributors come to this website every day, eager to share their expertise with the world. Unfortunately, they are met with the GitHub equivalent of a blank stare—not a single file describes the project, its goal, or anything of the sort.

This is not the Andrew McCullough I have come to know, and—dare I say—love.

**Comment by andrewmccullough** [comment]
Mr. Kerrigan,

This decision, while not intentional, suits my purposes quite well. You ask for a README.md to hold your hand through my inscrutable code, but perhaps you should consider whether you are worthy of such knowledge in a GitHub repository known only as "mastermind." My goals are far more nefarious than a simple README could hope to express.

On an unrelated note, if you've ever played the board game "Mastermind" (again, totally unrelated to this project), I'd encourage you to take a look at [this webpage](https://andrewmccullough.github.io/mastermind/) to kill some time.
